org: jhon64
app: mi-primer-projec
service: serverless-express-postgresql
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'
